# Generated by Django 5.1.4 on 2025-01-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Running', 'Running'), ('Cycling', 'Cycling'), ('Weightlifting', 'Weightlifting')], max_length=50)),
                ('duration', models.PositiveIntegerField()),
                ('distance', models.FloatField()),
                ('calories_burned', models.PositiveIntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
